### ISSUE TITLE
Wrong number of arguments

### ISSUE THREAD

**Issue by margaretjoanmiller** [Arian-D/consult-ps#1]
I tried downloading this package using the straight.el example but running the command produces the error `consult-ps: Wrong number of arguments: #<subr consult--async-refresh-timer>, 0`

**Comment by Arian-D** [comment]
I had completely forgotten about this project lol. Try `straight-pull-package` and `straight-rebuild-package`ing `consult-ps`. Let me know if the issue is resolved with https://github.com/Arian-D/consult-ps/commit/958f1102bfad35183ef1d9a067fb92c878ff29d8

**Comment by margaretjoanmiller** [comment]
Seems to be! Thanks!
